spring.application.name=appointment-service

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/whatsapp_crm_appointments
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Flyway
spring.flyway.enabled=true

server.port=8081

patient-service.url=http://localhost:8080
doctor-service.url=http://localhost:8082